//Not all compilers like single quotes for paths. Better use paths without blanks.
//You can uncomment the following lines, belonging to the theme you want to use, and keep the others commented.
//If multiple themes are uncommented, the compiler should display "Identifier redeclared" errors.
//The compiler may require the full paths to theme directories to be added at project search paths, e.g.: D:\DynTFTThemes\<ThemeName>\ .  Otherwise, it searches at project level as before.

//Keep in mind that custom colors are not part of a color theme. Please use color constants like CL_DynTFTArrowButton_Background or CL_DynTFTProgressBar_Progress instead of their numerical value, in order for a theme to be applied.

{$I D:\DynTFTThemes\System\UserColors.inc}
{$I D:\DynTFTThemes\System\DynTFTColorTheme.inc}


//{$I D:\DynTFTThemes\Copper\UserColors.inc}
//{$I D:\DynTFTThemes\Copper\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Charcoal\UserColors.inc}
//{$I D:\DynTFTThemes\Charcoal\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\RedCharcoal\UserColors.inc}
//{$I D:\DynTFTThemes\RedCharcoal\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\YellowCharcoal\UserColors.inc}
//{$I D:\DynTFTThemes\YellowCharcoal\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\LemonCharcoal\UserColors.inc}
//{$I D:\DynTFTThemes\LemonCharcoal\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\BlueCharcoal\UserColors.inc}
//{$I D:\DynTFTThemes\BlueCharcoal\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\GreenCharcoal\UserColors.inc}
//{$I D:\DynTFTThemes\GreenCharcoal\DynTFTColorTheme.inc}


//{$I D:\DynTFTThemes\Vision\UserColors.inc}
//{$I D:\DynTFTThemes\Vision\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Grass\UserColors.inc}
//{$I D:\DynTFTThemes\Grass\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Matrix\UserColors.inc}
//{$I D:\DynTFTThemes\Matrix\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Aurora\UserColors.inc}
//{$I D:\DynTFTThemes\Aurora\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Sea\UserColors.inc}
//{$I D:\DynTFTThemes\Sea\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Space\UserColors.inc}
//{$I D:\DynTFTThemes\Space\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Ocean\UserColors.inc}
//{$I D:\DynTFTThemes\Ocean\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Dawn\UserColors.inc}
//{$I D:\DynTFTThemes\Dawn\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Orchid\UserColors.inc}
//{$I D:\DynTFTThemes\Orchid\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Sand\UserColors.inc}
//{$I D:\DynTFTThemes\Sand\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Lava\UserColors.inc}
//{$I D:\DynTFTThemes\Lava\DynTFTColorTheme.inc}

//{$I D:\DynTFTThemes\Industrial\UserColors.inc}
//{$I D:\DynTFTThemes\Industrial\DynTFTColorTheme.inc}
