{   DynTFT  - graphic components for microcontrollers
    Copyright (C) 2017 VCC
    release date: 29 Dec 2017
    author: VCC

    This file is part of DynTFT project.

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}

//Generated by DynTFTCodeGen.


unit DynTFTGUIObjects;

{$IFNDEF IsMCU}
  {$DEFINE IsDesktop}
{$ENDIF}

{$IFDEF IsDesktop}
interface
{$ENDIF}

uses
  DynTFTTypes, DynTFTConsts,

//<DynTFTComponents>
  DynTFTButton,
  DynTFTArrowButton,
  DynTFTPanel,
  DynTFTCheckBox,
  DynTFTScrollBar,
  DynTFTItems,
  DynTFTListBox,
  DynTFTLabel,
  DynTFTRadioButton,
  DynTFTRadioGroup,
  DynTFTTabButton,
  DynTFTPageControl,
  DynTFTEdit,
  DynTFTKeyButton,
  DynTFTVirtualKeyboard,
  DynTFTComboBox,
  DynTFTTrackBar,
  DynTFTProgressBar,
  DynTFTMessageBox
//<EndOfDynTFTComponents> - Do not remove or modify this line!


  {$I DynTFTGUIAdditionalUnits.inc}
  ;


// Project name: GUI_Example_Unsized.dyntftcg //Do not delete or modify this line!

var
  ATestPageControl1: PDynTFTPageControl;
  ATestButton: PDynTFTButton;
  ATestArrowButton1: PDynTFTArrowButton;
  ATestArrowButton2: PDynTFTArrowButton;
  ATestArrowButton3: PDynTFTArrowButton;
  ATestArrowButton4: PDynTFTArrowButton;
  ATestArrowButton5: PDynTFTArrowButton;
  ATestArrowButton6: PDynTFTArrowButton;
  ATestArrowButton7: PDynTFTArrowButton;
  ATestArrowButton8: PDynTFTArrowButton;
  ATestButton2: PDynTFTButton;
  ATestArrowButton9: PDynTFTArrowButton;
  ATestArrowButton10: PDynTFTArrowButton;
  ATestArrowButton11: PDynTFTArrowButton;
  ATestArrowButton12: PDynTFTArrowButton;
  ATestArrowButton13: PDynTFTArrowButton;
  ATestArrowButton14: PDynTFTArrowButton;
  ATestArrowButton15: PDynTFTArrowButton;
  ATestArrowButton16: PDynTFTArrowButton;
  ATestButton3: PDynTFTButton;
  ATestCheckBox1: PDynTFTCheckBox;
  ATestCheckBox2: PDynTFTCheckBox;
  ATestCheckBox3: PDynTFTCheckBox;
  ATestCheckBox4: PDynTFTCheckBox;
  ATestCheckBox5: PDynTFTCheckBox;
  ATestCheckBox6: PDynTFTCheckBox;
  ATestCheckBox7: PDynTFTCheckBox;
  ATestCheckBox8: PDynTFTCheckBox;
  ATestPanel1: PDynTFTPanel;
  ATestPanel2: PDynTFTPanel;
  ATestPanel3: PDynTFTPanel;
  ATestScrollBar1: PDynTFTScrollBar;
  ATestScrollBar2: PDynTFTScrollBar;
  ATestScrollBar3: PDynTFTScrollBar;
  ATestListBox: PDynTFTListBox;
  ATestLabel1: PDynTFTLabel;
  ATestLabel2: PDynTFTLabel;
  ATestLabel3: PDynTFTLabel;
  ATestRadioGroup1: PDynTFTRadioGroup;
  ATestEdit1: PDynTFTEdit;
  ATestEdit2: PDynTFTEdit;
  ATestArrowButton17: PDynTFTArrowButton;
  ATestArrowButton18: PDynTFTArrowButton;
  btnCreateKeyboard: PDynTFTButton;
  ATestButton4: PDynTFTButton;
  ATestButton5: PDynTFTButton;
  ATestButton6: PDynTFTButton;
  ATestButton7: PDynTFTButton;
  ATestButton8: PDynTFTButton;
  AComboBox1: PDynTFTComboBox;
  ATestButton9: PDynTFTButton;
  ATrackBar1: PDynTFTTrackBar;
  ATrackBar2: PDynTFTTrackBar;
  ATrackBar3: PDynTFTTrackBar;
  ATrackBar4: PDynTFTTrackBar;
  AProgressBarH: PDynTFTProgressBar;
  AProgressBarV: PDynTFTProgressBar;
  ALabelH: PDynTFTLabel;
  ALabelV: PDynTFTLabel;
  btnMsgBox: PDynTFTButton;
  SelfDestroyButton: PDynTFTButton;
  AVirtualKeyboard: PDynTFTVirtualKeyboard;
  ATestPageControl2: PDynTFTPageControl;
  DynTFTRadioGroup0: PDynTFTRadioGroup;
  ATestPageControl3: PDynTFTPageControl;
  DynTFTComboBox0: PDynTFTComboBox;
  DynTFTLabel0: PDynTFTLabel;
  arrbtnDecItemIndex: PDynTFTArrowButton;
  arrbtnIncItemIndex: PDynTFTArrowButton;
  lblItemIndex: PDynTFTLabel;
  lstFileExplorer: PDynTFTListBox;
  cmbFileExplorerDrives: PDynTFTComboBox;

//RadioGroup code
type
  TRadioButtonCaption = string[CMaxRadioButtonStringLength];
  TRadioButtonCaptionArr = array{$IFDEF IsMCU}[0..0]{$ENDIF} of TRadioButtonCaption;

procedure PDynTFTRadioGroup_CreateAllRadioButtons(Left, Top, Width, Height, ButtonCount: Integer; Parent: PDynTFTRadioGroup; {$IFDEF IsMCU}var Captions: TRadioButtonCaptionArr{$ELSE} const Captions: array of TRadioButtonCaption{$ENDIF});

//PageControl code
type
  TTabButtonCaption = string[CMaxTabButtonStringLength];
  TTabButtonCaptionArr = array{$IFDEF IsMCU}[0..0]{$ENDIF} of TTabButtonCaption;
  TTabButtonIntegerArr = array{$IFDEF IsMCU}[0..0]{$ENDIF} of Integer;

procedure PDynTFTPageControl_CreateAllTabButtonsAsHorizontal(Left, Top, Height, PageCount: Integer; {$IFDEF IsMCU}var Lefts, Widths: TTabButtonIntegerArr {$ELSE} const Lefts, Widths: array of Integer{$ENDIF}; Parent: PDynTFTPageControl; {$IFDEF IsMCU}var Captions: TTabButtonCaptionArr{$ELSE} const Captions: array of TTabButtonCaption{$ENDIF});
procedure PDynTFTPageControl_CreateAllTabButtonsAsVertical(Left, Top, Width, Height, PageCount: Integer; Parent: PDynTFTPageControl; {$IFDEF IsMCU}var Captions: TTabButtonCaptionArr{$ELSE} const Captions: array of TTabButtonCaption{$ENDIF});


const
  // DynTFTRadioGroup
  CATestRadioGroup1_Captions: array[0..3 - 1] of TRadioButtonCaption = ('RadioButton 1 fp', 'RadioButton 2 fp', 'RadioButton 3 fp');
  CDynTFTRadioGroup0_Captions: array[0..2 - 1] of TRadioButtonCaption = ('First', 'Second');

  // DynTFTPageControl
  CATestPageControl1_Captions: array[0..3 - 1] of TTabButtonCaption = ('Tab 1', 'Tab 2', 'Tab 3');
  CATestPageControl1_ButtonLefts: array[0..3 - 1] of Integer = (0, 81, 162);
  CATestPageControl1_ButtonWidths: array[0..3 - 1] of Integer = (80, 80, 80);
  CATestPageControl2_Captions: array[0..4 - 1] of TTabButtonCaption = ('First tab', 'Second tab', 'Third tab', 'Fourth tab');
  CATestPageControl2_ButtonLefts: array[0..4 - 1] of Integer = (0, 0, 0, 0);
  CATestPageControl2_ButtonWidths: array[0..4 - 1] of Integer = (81, 81, 81, 81);
  CATestPageControl3_Captions: array[0..4 - 1] of TTabButtonCaption = ('First tab', 'Second tab', 'Third tab', 'Fourth tab');
  CATestPageControl3_ButtonLefts: array[0..4 - 1] of Integer = (0, 0, 0, 0);
  CATestPageControl3_ButtonWidths: array[0..4 - 1] of Integer = (81, 81, 81, 81);


const
  C_ATestButton_Caption = 'shapes';
  C_ATestButton2_Caption = 'Disabled';
  C_ATestButton3_Caption = 'Create button';
  C_ATestCheckBox1_Caption = 'Password Char';
  C_ATestCheckBox2_Caption = 'Disabled';
  C_ATestCheckBox3_Caption = 'ScrBar Visibility';
  C_ATestCheckBox4_Caption = 'ScrBar Enabling';
  C_ATestCheckBox5_Caption = 'rdBtn Visibility';
  C_ATestCheckBox6_Caption = 'LstBox Visibility';
  C_ATestCheckBox7_Caption = 'rdGrp Visibility';
  C_ATestCheckBox8_Caption = 'pag Visibility';
  C_ATestPanel1_Caption = 'Panel 1';
  C_ATestPanel2_Caption = 'Disabled';
  C_ATestPanel3_Caption = 'Panel 2';
  C_ATestListBox_Items_Strings_Item_0 = '0  zero';
  C_ATestListBox_Items_Strings_Item_1 = '1  one';
  C_ATestListBox_Items_Strings_Item_2 = '2  two';
  C_ATestListBox_Items_Strings_Item_3 = '3  three';
  C_ATestListBox_Items_Strings_Item_4 = '4  four';
  C_ATestListBox_Items_Strings_Item_5 = '5  five';
  C_ATestListBox_Items_Strings_Item_6 = '6  six';
  C_ATestListBox_Items_Strings_Item_7 = '7  seven';
  C_ATestListBox_Items_Strings_Item_8 = '8  eight';
  C_ATestListBox_Items_Strings_Item_9 = '9  nine';
  C_ATestListBox_Items_Strings_Item_10 = '10 ten';
  C_ATestListBox_Items_Strings_Item_11 = '11eleven';
  C_ATestListBox_Items_Strings_Item_12 = '12 twelve';
  C_ATestListBox_Items_Strings_Item_13 = '13 thirteen';
  C_ATestListBox_Items_Strings_Item_14 = '14 fourteen';
  C_ATestListBox_Items_Strings_Item_15 = '15 fifteen - fpWgJj';
  C_ATestListBox_Items_Strings_Item_16 = '----';
  C_ATestListBox_Items_Strings_Item_17 = 'abcdefghijklmnopqrstuvwxyz';
  C_ATestListBox_Items_Strings_Item_18 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLKMNOPQRSTUVWXYZ';
  C_ATestLabel1_Caption = 'lblDisabled';
  C_ATestLabel2_Caption = 'My label';
  C_ATestLabel3_Caption = 'Repainted area';
  C_ATestRadioGroup1_Caption = 'Some RadioGroup';
  C_ATestEdit1_Text = 'This is another long text for Edit.';
  C_btnCreateKeyboard_Caption = 'Create Keyboard';
  C_ATestButton4_Caption = 'DestroyTab';
  C_ATestButton5_Caption = 'DestroyPage';
  C_ATestButton6_Caption = 'DestroyRdBtn';
  C_ATestButton7_Caption = 'DestroyRdGrp';
  C_ATestButton8_Caption = 'Self Destroy';
  C_AComboBox1_ListBox_Items_Strings_Item_0 = 'one';
  C_AComboBox1_ListBox_Items_Strings_Item_1 = 'two';
  C_AComboBox1_ListBox_Items_Strings_Item_2 = 'three';
  C_AComboBox1_ListBox_Items_Strings_Item_3 = 'four';
  C_AComboBox1_ListBox_Items_Strings_Item_4 = 'five';
  C_AComboBox1_ListBox_Items_Strings_Item_5 = 'six';
  C_AComboBox1_ListBox_Items_Strings_Item_6 = 'seven';
  C_AComboBox1_ListBox_Items_Strings_Item_7 = 'eight';
  C_AComboBox1_ListBox_Items_Strings_Item_8 = 'nine';
  C_AComboBox1_ListBox_Items_Strings_Item_9 = 'ten';
  C_AComboBox1_ListBox_Items_Strings_Item_10 = 'eleven';
  C_AComboBox1_ListBox_Items_Strings_Item_11 = 'twelve';
  C_ATestButton9_Caption = 'Toggle editable cmb';
  C_ALabelH_Caption = '100';
  C_btnMsgBox_Caption = 'MsgBox';
  C_SelfDestroyButton_Caption = 'SelfDestroy';
  C_DynTFTRadioGroup0_Caption = 'DynTFTRadioGroup0';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_0 = 'one';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_1 = 'two';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_2 = 'three';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_3 = 'four';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_4 = 'five';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_5 = 'six';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_6 = 'seven';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_7 = 'eight';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_8 = 'nine';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_9 = 'ten';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_10 = 'eleven';
  C_DynTFTComboBox0_ListBox_Items_Strings_Item_11 = 'twelve';
  C_DynTFTLabel0_Caption = 'SearchBox';
  C_lblItemIndex_Caption = 'ItemIndex: -1';
  C_cmbFileExplorerDrives_Edit_Text = 'C:';

  {$IFDEF RTTIREG}
      CAllCreatedBinComponents: array[0..0] of ^PDynTFTBaseComponent = (nil);  // No binary component with global variable.
  {$ENDIF} // RTTIREG

implementation

procedure PDynTFTRadioGroup_CreateRadioButton(Left, Top, Width, Height: Integer; {$IFDEF IsMCU} var {$ENDIF}Caption: string; Parent: PDynTFTRadioGroup);
var
  radbtn: PDynTFTRadioButton;
begin
  radbtn := DynTFTRadioButton_Create(Parent^.BaseProps.ScreenIndex, Left, Top, Width, Height);
  radbtn^.Caption := Caption;
  DynTFTAddRadioButtonToRadioGroup(Parent, radbtn);
end;

procedure PDynTFTRadioGroup_CreateAllRadioButtons(Left, Top, Width, Height, ButtonCount: Integer; Parent: PDynTFTRadioGroup; {$IFDEF IsMCU}var Captions: TRadioButtonCaptionArr{$ELSE} const Captions: array of TRadioButtonCaption{$ENDIF});
var
  i, ButtonCount_1: Integer;
begin
  ButtonCount_1 := ButtonCount - 1;
  for i := 0 to ButtonCount_1 do
    PDynTFTRadioGroup_CreateRadioButton(Left, Top + i * Height, Width, Height, Captions[i], Parent);
end;

procedure PDynTFTPageControl_CreateTabButton(Left, Top, Width, Height: Integer; {$IFDEF IsMCU} var {$ENDIF}Caption: string; Parent: PDynTFTPageControl);
var
  tabbtn: PDynTFTTabButton;
begin
  tabbtn := DynTFTTabButton_Create(Parent^.BaseProps.ScreenIndex, Left, Top, Width, Height);
  tabbtn^.Caption := Caption;
  DynTFTAddTabButtonToPageControl(Parent, tabbtn);
end;

procedure PDynTFTPageControl_CreateAllTabButtonsAsHorizontal(Left, Top, Height, PageCount: Integer; {$IFDEF IsMCU}var Lefts, Widths: TTabButtonIntegerArr {$ELSE} const Lefts, Widths: array of Integer{$ENDIF}; Parent: PDynTFTPageControl; {$IFDEF IsMCU}var Captions: TTabButtonCaptionArr{$ELSE} const Captions: array of TTabButtonCaption{$ENDIF});
var
  i, ButtonCount_1: Integer;
begin
  ButtonCount_1 := PageCount - 1;
  for i := 0 to ButtonCount_1 do

    PDynTFTPageControl_CreateTabButton(Left + Lefts[i], Top, Widths[i], Height, Captions[i], Parent);
end;

procedure PDynTFTPageControl_CreateAllTabButtonsAsVertical(Left, Top, Width, Height, PageCount: Integer; Parent: PDynTFTPageControl; {$IFDEF IsMCU}var Captions: TTabButtonCaptionArr{$ELSE} const Captions: array of TTabButtonCaption{$ENDIF});
var
  i, ButtonCount_1: Integer;
begin
  ButtonCount_1 := PageCount - 1;
  for i := 0 to ButtonCount_1 do
    PDynTFTPageControl_CreateTabButton(Left, Top + i * Height, Width, Height, Captions[i], Parent);
end;

end.
