{   DynTFT  - graphic components for microcontrollers
    Copyright (C) 2017 VCC
    release date: 29 Dec 2017
    author: VCC

    This file is part of DynTFT project.

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}

//Generated by DynTFTCodeGen.

unit DynTFTGUIObjects;

{$IFNDEF IsMCU}
  {$DEFINE IsDesktop}
{$ENDIF}

{$IFDEF IsDesktop}
interface
{$ENDIF}

uses
  DynTFTButton, DynTFTArrowButton, DynTFTPanel, DynTFTCheckBox, DynTFTScrollBar,
  DynTFTItems, DynTFTListBox, DynTFTLabel, DynTFTRadioButton, DynTFTRadioGroup,
  DynTFTTabButton, DynTFTPageControl, DynTFTEdit, DynTFTVirtualKeyboard,
  DynTFTComboBox, DynTFTTrackBar, DynTFTProgressBar
  {$I DynTFTGUIAdditionalUnits.inc}
  ;


// Project name: GUI_Example_Unsized.dyntftcg //Do not delete or modify this line!

var
  ATestPageControl1: PDynTFTPageControl;
  ATestButton: PDynTFTButton;
  ATestArrowButton1: PDynTFTArrowButton;
  ATestArrowButton2: PDynTFTArrowButton;
  ATestArrowButton3: PDynTFTArrowButton;
  ATestArrowButton4: PDynTFTArrowButton;
  ATestArrowButton5: PDynTFTArrowButton;
  ATestArrowButton6: PDynTFTArrowButton;
  ATestArrowButton7: PDynTFTArrowButton;
  ATestArrowButton8: PDynTFTArrowButton;
  ATestButton2: PDynTFTButton;
  ATestArrowButton9: PDynTFTArrowButton;
  ATestArrowButton10: PDynTFTArrowButton;
  ATestArrowButton11: PDynTFTArrowButton;
  ATestArrowButton12: PDynTFTArrowButton;
  ATestArrowButton13: PDynTFTArrowButton;
  ATestArrowButton14: PDynTFTArrowButton;
  ATestArrowButton15: PDynTFTArrowButton;
  ATestArrowButton16: PDynTFTArrowButton;
  ATestButton3: PDynTFTButton;
  ATestCheckBox1: PDynTFTCheckBox;
  ATestCheckBox2: PDynTFTCheckBox;
  ATestCheckBox3: PDynTFTCheckBox;
  ATestCheckBox4: PDynTFTCheckBox;
  ATestCheckBox5: PDynTFTCheckBox;
  ATestCheckBox6: PDynTFTCheckBox;
  ATestCheckBox7: PDynTFTCheckBox;
  ATestCheckBox8: PDynTFTCheckBox;
  ATestPanel1: PDynTFTPanel;
  ATestPanel2: PDynTFTPanel;
  ATestPanel3: PDynTFTPanel;
  ATestScrollBar1: PDynTFTScrollBar;
  ATestScrollBar2: PDynTFTScrollBar;
  ATestScrollBar3: PDynTFTScrollBar;
  ATestListBox: PDynTFTListBox;
  ATestLabel1: PDynTFTLabel;
  ATestLabel2: PDynTFTLabel;
  ATestLabel3: PDynTFTLabel;
  ATestRadioGroup1: PDynTFTRadioGroup;
  ATestEdit1: PDynTFTEdit;
  ATestEdit2: PDynTFTEdit;
  ATestArrowButton17: PDynTFTArrowButton;
  ATestArrowButton18: PDynTFTArrowButton;
  btnCreateKeyboard: PDynTFTButton;
  ATestButton4: PDynTFTButton;
  ATestButton5: PDynTFTButton;
  ATestButton6: PDynTFTButton;
  ATestButton7: PDynTFTButton;
  ATestButton8: PDynTFTButton;
  AComboBox1: PDynTFTComboBox;
  ATestButton9: PDynTFTButton;
  ATrackBar1: PDynTFTTrackBar;
  ATrackBar2: PDynTFTTrackBar;
  ATrackBar3: PDynTFTTrackBar;
  ATrackBar4: PDynTFTTrackBar;
  AProgressBarH: PDynTFTProgressBar;
  AProgressBarV: PDynTFTProgressBar;
  ALabelH: PDynTFTLabel;
  ALabelV: PDynTFTLabel;
  btnMsgBox: PDynTFTButton;
  SelfDestroyButton: PDynTFTButton;
  AVirtualKeyboard: PDynTFTVirtualKeyboard;
  ATestPageControl2: PDynTFTPageControl;
  DynTFTRadioGroup0: PDynTFTRadioGroup;
  ATestPageControl3: PDynTFTPageControl;
  DynTFTComboBox0: PDynTFTComboBox;

implementation

end.
